#!/bin/bash
tail -n 10 /etc/passwd >> 4-lastlines
echo tail -n 10 /etc/passwd
tail -n 10 /etc/passwd >> 4-lastlines
echo tail -n 10 /etc/passwd >> 4-lastlines
echo tail -n 10 /etc/passwd
tail -n 10 /etc/passwd
